//! Golden-file suites.
//!
//! Adding a test is adding two files: a program and the output it should
//! produce. `tests/cases/*.out` holds what CPython prints for that program —
//! generated by running `python3` on it — so the expectations are not just
//! minipy agreeing with itself. `tests/errors/*.err` holds the error report,
//! which is minipy's own format.

use std::fs;
use std::path::{Path, PathBuf};

fn programs(dir: &str) -> Vec<PathBuf> {
    let mut found: Vec<PathBuf> = fs::read_dir(Path::new(env!("CARGO_MANIFEST_DIR")).join(dir))
        .unwrap_or_else(|e| panic!("could not read {dir}: {e}"))
        .map(|entry| entry.expect("could not read a directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "py"))
        .collect();
    found.sort();
    assert!(!found.is_empty(), "no programs found in {dir}");
    found
}

fn read(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|e| panic!("could not read {}: {e}", path.display()))
}

/// Report every mismatch at once; one failing case should not hide the rest.
fn assert_no_failures(failures: Vec<String>) {
    if !failures.is_empty() {
        panic!(
            "\n\n{}\n{} case(s) failed\n",
            failures.join("\n"),
            failures.len()
        );
    }
}

#[test]
fn cases_produce_the_output_cpython_does() {
    let failures = minipy::on_interpreter_stack(|| {
        let mut failures = Vec::new();
        for program in programs("tests/cases") {
            let expected = read(&program.with_extension("out"));
            let actual = match minipy::capture(&read(&program)) {
                Ok(output) => output,
                Err(err) => {
                    failures.push(format!(
                        "{}: failed to run: {err}",
                        program.file_name().unwrap().to_string_lossy()
                    ));
                    continue;
                }
            };
            if actual != expected {
                failures.push(format!(
                    "{}:\n--- expected ---\n{expected}--- actual ---\n{actual}",
                    program.file_name().unwrap().to_string_lossy()
                ));
            }
        }
        failures
    });
    assert_no_failures(failures);
}

#[test]
fn errors_are_reported_with_the_right_kind_line_and_message() {
    let failures = minipy::on_interpreter_stack(|| {
        let mut failures = Vec::new();
        for program in programs("tests/errors") {
            let name = program.file_name().unwrap().to_string_lossy().to_string();
            let expected = read(&program.with_extension("err"));
            // The expectation records the path as it appears from the repo root.
            let reported_as = format!("tests/errors/{name}");

            match minipy::capture(&read(&program)) {
                Ok(output) => {
                    failures.push(format!(
                        "{name}: expected an error, but it printed:\n{output}"
                    ));
                }
                Err(err) => {
                    let actual = format!("{}\n", err.report(&reported_as));
                    if actual != expected {
                        failures.push(format!(
                            "{name}:\n--- expected ---\n{expected}--- actual ---\n{actual}"
                        ));
                    }
                }
            }
        }
        failures
    });
    assert_no_failures(failures);
}
